### ISSUE TITLE
errors in download_ranking_images.py

### ISSUE THREAD

**Issue by j777shin** [yiling-chen/flickr-cropping-dataset#8]
I can run download_images.py just fine
but download_ranking_images.py seems to have trouble.

Traceback (most recent call last):
  File "download_ranking_images.py", line 49, in <module>
    pool.map(fetch_image, URLs)
  File "/home/rachel/anaconda3/envs/flickr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/rachel/anaconda3/envs/flickr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: cannot identify image file '/tmp/tmpbD3O8_.jpg'

Could you give me the solution for this problem?
Thank you

**Comment by j777shin** [comment]
I just resolved this issue by copying new codes in download_images.py
if you change 'download_ranking_images.py', that would be great
